volumes:
  postgres_data:
  minio_data:

services:
  mlflow:
    build:
      context: ../..
      dockerfile: infra/dockerfiles/mlflow.Dockerfile
    image: mlflow
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123

  create-bucket:
    build:
      context: ../..
      dockerfile: infra/dockerfiles/minio-client.Dockerfile
